apiVersion: v1
kind: Secret
metadata:
  name: demo-db-info
  namespace: petclinic-prod
type: Opaque
data:
  host: ZGVtby1kYg==          # demo-db
  port: NTQzMg==             # 5432
  provider: cG9zdGdyZXNxbA== # postgresql
  type: cG9zdGdyZXNxbA==     # postgresql



